### PR TITLE
Add #presence method, as per Rails version

### PR DESCRIPTION
**Pull request by Bogadon**
Thanks for the awesome library. Makes switching between ruby and JS much easier on the brain :).

Rails presence: http://api.rubyonrails.org/classes/Object.html#method-i-presence

These are currently opt-in by explicitly requiring the files only; I am not sure how to go about including them in the comprehensive array.js, object.js files. 

I found I missed presence() for handling empty collections, things like:
`
collection.presence() || "no components to render"`

The string and number versions are probably most useful for duck typing.

### CODE REVIEW

**Comment by westonganger** [comment]
My main problem with this solution is it wont work with null, undefined, etc.. Personally, I think this method would make more sense to add it to the Core Functions (this section could possibly be reworked and expanded to include more of the methods on the link you have given me). It could be used like so:

```javascript
var Rearmed = require('rearmed-js/core');

Rearmed.presence(myVar);
```

But I really like being able to duck type i like you added. It would be perfect for handling zero's in if statements. Maybe this is a good case to have both ways, what do you think?

**Changes Required:**

* If you want to work on this library you should only be editing the `src` folder and use the provided `gulp` task. Everything will make a lot more sense after you know that. Sorry the folder structure is so complicated, JS can get nasty like this sometimes. 
* I don't like how number presence is handled. I don't need Rails exact behaviour, I want expected, natural feeling behaviour. I think NaN should be rejected.

**Comment by Bogadon** [comment]
Thanks for the feedback; having looked up gulp, the library makes more sense :). I am new to modern JS.

Having referenced the way rails does it: https://github.com/rails/rails/blob/cab6ba4e1bf2abf6a5fb83f2f28e2a8482350bbd/activesupport/lib/active_support/core_ext/object/blank.rb

I have amended the PR to only patch Object and Number, and include together with present and blank. Does this seem reasonable?

When I run `gulp`, each task gives me an error like: 
[14:05:12] GulpUglifyError: unable to minify JavaScript
Caused by: DefaultsError: `preserveComments` is not a supported option
File: /home/developer/Projects/rearmed-js/object.js

Although it seems to have worked, though has not created the standalone versions of object/blank or number/blank. Have been googling the error, but so far nothing :(.

**Comment by westonganger** [comment]
We need to make very concious decisions about what methods to add in client side libraries. I do not want to bloat the library on useless methods. Once you know javascript better you will understand these methods will not be useful. 

I am going to implement a more robust "Core" section to include these types of methods as its the only sane way I can think of handling this.

**Comment by Bogadon** [comment]
My regularly encountered use case is to save 3 lines of code in situations like:

```
myFunction() {
  return some.method().presence()
}
```

vs

```
myFunction() {
  let myVar = some.method()
  if (!myVar.empty()) {
    return myVar
  }
}
```

I think the former is clearer and more elegant, if you work in a team of Rails devs.

**Comment by westonganger** [comment]
Please see the latest master which implements what you want. I have removed the Core section and added a Generic section which contains `presence`.

**Pull request closed without merging**
